version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias..."

  build:
    commands:
      - echo "Construyendo imagen Docker..."
      - docker build -t devops-data .

  post_build:
    commands:
      - echo "Ejecutando contenedor..."
      - docker run devops-data

artifacts:
  files:
    - '**/*'
