version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias..."

  build:
    commands:
      - echo "Construyendo imagen Docker..."
      - docker build -t flask-app ./app

  post_build:
    commands:
      - echo "Ejecutando contenedor..."
      - chmod +x deploy.sh #se vuelva ejecutable
      - ./deploy.sh

artifacts:
  files:
    - '**/*'
